#!/usr/bin/env python3
"""
Claude Code Review Script
Analyzes PR changes using Claude API and posts review comments.
"""

import os
import sys
from anthropic import Anthropic
from github import Github

def get_pr_diff(repo, pr_number):
    """Fetch the PR diff from GitHub."""
    pr = repo.get_pull(pr_number)
    files = pr.get_files()

    diff_content = []
    for file in files:
        diff_content.append(f"\n{'='*80}")
        diff_content.append(f"File: {file.filename}")
        diff_content.append(f"Status: {file.status}")
        diff_content.append(f"Changes: +{file.additions} -{file.deletions}")
        diff_content.append(f"{'='*80}\n")
        if file.patch:
            diff_content.append(file.patch)

    return "\n".join(diff_content), pr

def review_with_claude(diff_content):
    """Send the diff to Claude for code review."""
    client = Anthropic(api_key=os.environ['ANTHROPIC_API_KEY'])

    prompt = f"""You are an expert code reviewer. Please review the following pull request changes and provide constructive feedback.

Focus on:
1. **Code Quality**: Clean code, readability, maintainability
2. **Best Practices**: Language-specific conventions and patterns
3. **Potential Bugs**: Logic errors, edge cases, error handling
4. **Performance**: Inefficient algorithms or operations
5. **Security**: Common vulnerabilities (if applicable)
6. **Testing**: Whether changes need tests or improve testability
7. **Documentation**: Code comments and documentation needs

Provide your review in the following format:
- Start with an overall summary
- List specific issues or suggestions with file names and line references when possible
- Be constructive and specific
- Highlight positive aspects too

Pull Request Changes:
{diff_content}
"""

    message = client.messages.create(
        model="claude-sonnet-4-5-20250929",
        max_tokens=4096,
        messages=[
            {"role": "user", "content": prompt}
        ]
    )

    return message.content[0].text

def post_review_comment(pr, review_text):
    """Post the review as a comment on the PR."""
    comment_body = f"""## 🤖 Claude Code Review

{review_text}

---
*This review was automatically generated by Claude AI. Please use your judgment when addressing the feedback.*
"""
    pr.create_issue_comment(comment_body)

def main():
    """Main function to orchestrate the code review process."""
    try:
        # Get environment variables
        github_token = os.environ['GITHUB_TOKEN']
        pr_number = int(os.environ['PR_NUMBER'])
        repo_name = os.environ['REPO_NAME']

        # Initialize GitHub client
        g = Github(github_token)
        repo = g.get_repo(repo_name)

        print(f"Fetching PR #{pr_number} from {repo_name}...")
        diff_content, pr = get_pr_diff(repo, pr_number)

        if not diff_content.strip():
            print("No changes found in PR. Skipping review.")
            return

        print("Sending changes to Claude for review...")
        review = review_with_claude(diff_content)

        print("Posting review comment to PR...")
        post_review_comment(pr, review)

        print("✓ Code review completed successfully!")

    except Exception as e:
        print(f"Error during code review: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()
