#!/usr/bin/env python3
"""
Gemini Code Review Script
Analyzes PR changes using Google Gemini API and posts review comments.
"""

import os
import sys
from google import genai
from github import Github, Auth

def get_pr_diff(repo, pr_number):
    """Fetch the PR diff from GitHub."""
    pr = repo.get_pull(pr_number)
    files = pr.get_files()

    diff_content = []
    for file in files:
        diff_content.append(f"\n{'='*80}")
        diff_content.append(f"File: {file.filename}")
        diff_content.append(f"Status: {file.status}")
        diff_content.append(f"Changes: +{file.additions} -{file.deletions}")
        diff_content.append(f"{'='*80}\n")
        if file.patch:
            diff_content.append(file.patch)

    return "\n".join(diff_content), pr

def review_with_gemini(diff_content, api_key):
    """Send the diff to Gemini for code review."""
    
    client = genai.Client(api_key=api_key)
    
    # Priority: Flash (fast/efficient) -> Pro (stronger reasoning) -> Legacy
    model_names = ['gemini-2.5-flash', 'gemini-2.5-flash-lite', 'gemini-2.5-pro']
    
    prompt = f"""You are an expert code reviewer. Please review the following pull request changes and provide constructive feedback.

Focus on:
1. **Code Quality**: Clean code, readability, maintainability
2. **Best Practices**: Language-specific conventions and patterns
3. **Potential Bugs**: Logic errors, edge cases, error handling
4. **Performance**: Inefficient algorithms or operations
5. **Security**: Common vulnerabilities (if applicable)
6. **Testing**: Whether changes need tests or improve testability
7. **Documentation**: Code comments and documentation needs

Provide your review in the following format:
- Start with an overall summary
- List specific issues or suggestions with file names and line references when possible
- Be constructive and specific
- Highlight positive aspects too

Pull Request Changes:
{diff_content}
"""

    for name in model_names:
        try:
            print(f"Attempting to generate review with model: {name}")
            response = client.models.generate_content(
                model=name,
                contents=prompt
            )
            return response.text
        except Exception as e:
            print(f"Warning: Failed with {name}: {e}")
            
    print("Error: Could not generate review with any Gemini models. Please check your API key and quota.", file=sys.stderr)
    sys.exit(1)

def post_review_comment(pr, review_text):
    """Post the review as a comment on the PR."""
    comment_body = f"""## ♊ Gemini Code Review

{review_text}

---
*This review was automatically generated by Google Gemini AI.*
"""
    pr.create_issue_comment(comment_body)

def main():
    """Main function to orchestrate the code review process."""
    try:
        # Get environment variables with stripping
        github_token = os.environ.get('GITHUB_TOKEN', '').strip()
        gemini_key = os.environ.get('GEMINI_API_KEY', '').strip()
        pr_number = int(os.environ.get('PR_NUMBER', '0'))
        repo_name = os.environ.get('REPO_NAME', '').strip()

        # Debug logging (masked)
        print(f"Debug: PR_NUMBER={pr_number}")
        print(f"Debug: REPO_NAME={repo_name}")
        if gemini_key:
            print(f"Debug: GEMINI_API_KEY found (starts with: {gemini_key[:4]}...)")
        else:
            print("Debug: GEMINI_API_KEY not found")

        if not github_token or not gemini_key or not repo_name or pr_number == 0:
            print("Error: Missing required environment variables. Please check your GitHub Repository Secrets (GEMINI_API_KEY).", file=sys.stderr)
            sys.exit(1)

        # Initialize GitHub client
        auth = Auth.Token(github_token)
        g = Github(auth=auth)
        repo = g.get_repo(repo_name)

        print(f"Fetching PR #{pr_number} from {repo_name}...")
        diff_content, pr = get_pr_diff(repo, pr_number)

        if not diff_content.strip():
            print("No changes found in PR. Skipping review.")
            return

        print("Sending changes to Gemini for review...")
        review = review_with_gemini(diff_content, gemini_key)

        print("Posting review comment to PR...")
        post_review_comment(pr, review)

        print("✓ Code review completed successfully!")

    except Exception as e:
        print(f"Error during code review: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()
